### ISSUE TITLE
InShorts image link 

### ISSUE THREAD

**Issue by rahulpandey1501** [iSumitBanik/COVID19-India-Data-API#5]
`div class="news-card-image" style="background-image: url('https://static.getinpix.com/public/images/v1/variants/jpg/m/2020/06_jun/2_tue/img_1591112201143_884.jpg')"`

In the above element, we get the image from style = 
logic `get('style')[23:-3]`  but this logic fails for above because it trims url to `.jp`
instead, can we do something like start with index `http` and ends with `'` ? to make less error prone

**Comment by iSumitBanik** [comment]
It's working well. 😄

**Comment by iSumitBanik** [comment]
Alright, Thanks for raising this issue. 
It's Fixed Now.
